
services:
  backend:
    build: 
      context: .
      dockerfile: ./META/backend/Dockerfile
    container_name: backend
    volumes:
      - ./src/backend:/backend
      - ${BACKEND_DATA_PATH}:${BACKEND_INNER_PATH}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    command: python3 setup.py
    env_file:
      - .env
    networks:
      template_network:
        ipv4_address: ${BACKEND_IP}

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: .\META\frontWeb\Dockerfile
  #   container_name: frontend
  #   volumes:
  #     - ./src/clientWeb:/web
  #   ports:
  #     - ${FRONT_WEB_PORT}:${FRONT_WEB_PORT}
  #   command: sh start_up.sh
  #   env_file:
  #     - .env
  #   networks:
  #     template_network:
  #       ipv4_address: ${FRONTEND_IP}

  # front_mb:
  #   build:
  #     context: .
  #     dockerfile: .\META\frontMB\Dockerfile
  #   container_name: front_mb
  #   volumes:
  #     - ./src/clientMB:/web
  #   ports:
  #     - ${FRONT_MB_PORT}:${FRONT_MB_PORT}
  #   command: sh /web/start_up.sh
  #   env_file:
  #     - .env
  #   networks:
  #     template_network:
  #       ipv4_address: ${FRONTMB_IP}

  db:
    image: mysql:8.0
    restart: always
    container_name: db
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ./META/DB/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      template_network:
        ipv4_address: ${DB_IP}
      
  redis:
    build:
      context: .
      dockerfile: ./META/redis/Dockerfile
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./META/redis/redis.conf:/etc/redis/redis.conf:ro
      - ${REDIS_DATA_PATH}/redis/data:/data
      - ${REDIS_DATA_PATH}/redis/logs:/logs
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    env_file:
      ./.env
    networks:
      template_network:
        ipv4_address: ${REDIS_IP}
  web:
    image: nginx:1.25.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volumes:
      - ./META/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./META/nginx/hosts:/etc/hosts:ro
      # - ./META/nginx/user_web:/user/web:ro
      - ${HTML_ROOT}:/www:ro
      # - ${IOT_DATA_PATH}/nginx:/var/log/nginx
      # - /etc/letsencrypt/archive/manager.woozatop.com/fullchain2.pem:/ssl_pem/server.crt:ro
      # - /etc/letsencrypt/archive/manager.woozatop.com/privkey2.pem:/ssl_pem/server.key:ro
    env_file:
      ./.env
    networks:
      hx_net:
        ipv4_address: 173.0.0.8

networks:
  template_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${BASE_IP}.0.0.0/16