# Generated by Django 4.2.4 on 2024-05-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '笔记',
                'db_table': 'notebook_docs',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='userbooksmodel',
            options={'ordering': ['id'], 'verbose_name': '笔记本'},
        ),
        migrations.CreateModel(
            name='BookTocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc', models.JSONField(null=True, verbose_name='目录')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.userbooksmodel')),
            ],
            options={
                'verbose_name': '目录',
                'db_table': 'notebook_toc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='doc_images', verbose_name='图片')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.bookdocsmodel')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'notebook_images',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bookdocsmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.userbooksmodel'),
        ),
    ]
