# Generated by Django 4.2.4 on 2024-05-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_bookdocsmodel_alter_userbooksmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktocmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.userbooksmodel', unique=True),
        ),
    ]
