# Generated by Django 4.2.4 on 2024-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_booktocmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktocmodel',
            name='toc',
            field=models.TextField(null=True, verbose_name='目录'),
        ),
    ]
