# Generated by Django 4.2.4 on 2024-05-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_alter_booktocmodel_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimages',
            name='doc_id',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='notebook.bookdocsmodel'),
            preserve_default=False,
        ),
    ]
