# Generated by Django 4.2.4 on 2024-05-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_bookimages_doc_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookImages',
            new_name='DocImages',
        ),
        migrations.RenameField(
            model_name='docimages',
            old_name='doc_id',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='docimages',
            old_name='images',
            new_name='image',
        ),
    ]
