# Generated by Django 4.2.4 on 2024-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_rename_bookimages_docimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docimages',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='docimages',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
