# Generated by Django 4.2.4 on 2024-05-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_docimages_create_time_docimages_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docimages',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.userbooksmodel'),
        ),
    ]
