# Generated by Django 4.2.4 on 2024-06-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appusermodel_managers_alter_appusermodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontMenuModel',
            fields=[
                ('item_key', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('item_title', models.CharField(max_length=100)),
                ('item_url', models.CharField(default=None, max_length=100, null=True)),
                ('sort_seq', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item_description', models.TextField()),
                ('father_menu_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.frontmenumodel')),
            ],
            options={
                'verbose_name': '前端菜单',
                'db_table': 'front_end_menu',
                'ordering': ['sort_seq'],
            },
        ),
    ]
