# Generated by Django 4.2.4 on 2024-06-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_alter_appusermodel_managers_alter_appusermodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroupExpander',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Group Extension',
                'verbose_name_plural': 'Group Extensions',
                'db_table': 'auth_group_expander',
            },
        ),
    ]
