# Generated by Django 4.2.4 on 2024-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_authgroupexpander'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroupexpander',
            name='outer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
