# Generated by Django 4.2.4 on 2024-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_frontmenumodel_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_url',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
