# Generated by Django 4.2.4 on 2024-06-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_frontmenumodel_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontmenumodel',
            options={'ordering': ['sort_seq'], 'verbose_name': 'front-end menu'},
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='father_menu_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.frontmenumodel', verbose_name='father menu id'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_description',
            field=models.TextField(default=None, null=True, verbose_name='item description'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_key',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='item key'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_title',
            field=models.CharField(max_length=100, verbose_name='item title'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='item_url',
            field=models.CharField(max_length=100, verbose_name='item url'),
        ),
        migrations.AlterField(
            model_name='frontmenumodel',
            name='sort_seq',
            field=models.IntegerField(default=0, verbose_name='sort seq'),
        ),
    ]
